name: Update keys.json

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  update-keys:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to use Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to use Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run keys.py script
      run: python keys.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'coolnerdycoder'
        git config --global user.email 'anukul.tripathi@gmail.com'
        git add keys.json
        git commit -m 'Update keys.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
